name: email_test.yml
on:
  push:
    branches: ['*']

jobs:
  emailTest:
    runs-on: windows-latest
    permissions:
      issues: write
    steps:
      - name: Create issue on failure
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const runUrl = `${context.serverUrl}/${owner}/${repo}/actions/runs/${context.runId}`;

            await github.rest.issues.create({
              owner,
              repo,
              title: 'Test issue',
              body: `See run: ${runUrl}\n@MakotoE`,
            });